[package]
name = "vimdecrypt"
version = "0.1.1"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
documentation = "https://docs.rs/vimdecrypt"
homepage = "https://github.com/SirVer/vimdecrypt-rs"
repository = "https://github.com/SirVer/vimdecrypt-rs"
readme = "README.md"
keywords = ["vim", "vimcrypt", "vimdecrypt", "decrypt", "crypt"]
description = "A rust library and command line tool to read encrypted Vim files."
license = "MIT"
exclude = [
  ".gitignore",
  ".travis.yml",
  "watcher.lua",
]

[dependencies]
blowfish = "0.3.0"
clap = "2.31.2"
failure = "0.1.1"
generic-array = "0.9.0"
rpassword = "2.0.0"
sha2 = "0.7.1"
